name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint numpy matplotlib pandas bokeh
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --output=lint.txt || true
    - name: Print Pylint Output
      run: cat lint.txt
    - name: Extract and Print Pylint Score
      run: |
        score=$(grep -o "rated at [0-9]*\.[0-9]*/10" lint.txt | tail -1)
        echo "Pylint Score: $score"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lint.txt
        path: lint.txt
