name: Pylint Score

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      id: pylint
      run: |
        pylint_score=$(pylint YOUR_PACKAGE_NAME | tee pylint_output.txt | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
        echo ::set-output name=score::$pylint_score

    - name: Append pylint score to file
      run: |
        echo "Run ID: ${{ github.run_id }} | Pylint Score: ${{ steps.pylint.outputs.score }}" >> pylint_scores.txt
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add pylint_scores.txt
        git commit -m "Update pylint score"
        git push
